Create works and about me sections
Abdelaziz-Ali/Portfolio pull request #3
Opened 2022-12-04 03:09 UTC by Abdelaziz-Ali

2022-12-05 09:31 UTC, medaminedev66 requested changes
Hi @Abdelaziz-Ali, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a PR that does not have a PR description. Kindly add a descriptive pull request description of what you have done in this pull request so that others can read what is being worked on. Check out this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 
to learn how to do this and then add a descriptive description to your pull request.
- Your project's readme misses the section Future Features.  Kindly add the section Future Features to your Readme, including 1-3 potential features to be added.
- According to general requirements,  the **template logo** in Readme should be removed. Optionally, you can replace it with your own logo if they have one.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 10:13 UTC, medaminedev66 approved these changes
Hi  @Abdelaziz-Ali,

Your project looks great. You can implement the changes requested in the review above and your PR will be approved.

2022-12-05 15:10 UTC, Abdelaziz-Ali commented
I have done the changes as requested Thank you.

2022-12-05 16:44 UTC, algerina requested changes
Hi @Abdelaziz-Ali , 

You've done an amazing job, I'm impressed fir 👏 💯 👍
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights
  -  Your project looks awesome!
  -  You have a descriptive Pull Request
  - No Linter errors!
  
<img src="https://media3.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy-downsized-medium.gif"/>

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.




Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-05 16:44 UTC, algerina commented on index.html
> +        <h1 class="aboutHeader">About</h1>
- [ ] You did a great job, please consider using a header tag `hx` instead of `h1` in this section. This way it will be semantically correct and the screen readers and other technologies will thank you. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.
 There should be just one h1 in an HTML file, for SEO(Search Engine Optimization) and web accessibility purposes.

2022-12-05 16:44 UTC, algerina commented on index.html
> +    <section class="contactMe"></section>
- [ ] Kindly consider wrapping all the cards in a section and use `display:grid` as in the project requirements.

2022-12-07 00:04 UTC, merged

2022-12-07 02:37 UTC, Tadesse-Alemayehu reviewed
### Hi @Abdelaziz-Ali 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. 🙏
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._